### ISSUE TITLE
500 server error using item.get

### ISSUE THREAD

**Issue by syntax53** [lukecyca/pyzabbix#102]
```
Sending: {
    "params": [
        {
            "output": [
                "name"
            ],
            "search": {
                "name": "Interface VLAN"
            }
        }
    ],
    "jsonrpc": "2.0",
    "method": "item.get",
    "auth": "blahsomethingblah",
    "id": 1
}
```
```
Response Code: 500
Traceback (most recent call last):
  File "zabbix_test.py", line 21, in <module>
    items = zapi.item.get({'output': ['name'], 'search': {'name': 'Interface VLAN'}})
  File "/usr/local/lib/python2.7/dist-packages/pyzabbix/__init__.py", line 157, in fn
    args or kwargs
  File "/usr/local/lib/python2.7/dist-packages/pyzabbix/__init__.py", line 109, in do_request
    response.raise_for_status()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://127.0.0.1/zabbix/api_jsonrpc.php/api_jsonrpc.php
```

**Comment by syntax53** [comment]
I just noticed the "/api_jsonrpc.php/api_jsonrpc.php" in the url after posting that and thought it was weird.  The url I had configured works because I can retrieve hosts using host.get.  However, I modified the url anyway and still get "500 Server Error: Internal Server Error for url: http://127.0.0.1/zabbix/api_jsonrpc.php"

**Comment by syntax53** [comment]
I see I had to change the syntax from
`items = zapi.item.get({'output':['name'], 'search':{'name':'Interface VLAN'}})`
to:
`items = zapi.item.get(output=['name'], search={'name':'Interface VLAN'})`

This resulted in the request being slightly different:
```
Sending: {
    "params": {
        "output": [
            "name"
        ],
        "search": {
            "name": "Interface VLAN"
        }
    },
    "jsonrpc": "2.0",
    "method": "item.get",
    "auth": "yadayada",
    "id": 1
}

```
