### ISSUE TITLE
delete trigger failed

### ISSUE THREAD

**Issue by qzmone** [lukecyca/pyzabbix#122]
def delete_trigger(trigger_name):
    trigger = trigger_exist_or_not(trigger_name)
    if not trigger:
        return
    result = zapi.trigger.delete(triggerids=trigger[0]['triggerid'])
    return result

Traceback (most recent call last):
  File "D:/Coding/ping_fabric_zabbix.py", line 200, in <module>
    print(delete_trigger('123'))
  File "D:/Coding/ping_fabric_zabbix.py", line 90, in delete_trigger
    result = zapi.trigger.delete(triggerids=trigger[0]['triggerid'])
  File "C:\Python36\lib\site-packages\pyzabbix\__init__.py", line 166, in fn
    args or kwargs
  File "C:\Python36\lib\site-packages\pyzabbix\__init__.py", line 143, in do_request
    raise ZabbixAPIException(msg, response_json['error']['code'])
pyzabbix.ZabbixAPIException: ('Error -32500: Application error., SQL statement execution has failed "DELETE FROM profiles WHERE idx=\'web.events.filter.triggerid\' AND value_id=Array"', -32500)

**Comment by paalbra** [comment]
You need to add more info. What's your Zabbix version and what's `trigger[0]['triggerid']`

You should also format your code/output for better readability:
https://guides.github.com/features/mastering-markdown/
