### ISSUE TITLE
Wrong error handling

### ISSUE THREAD

**Issue by nijel** [lukecyca/pyzabbix#125]
When connection fails with ``ConnectionRefusedError``, the logging code crashes:

```pytb
Traceback (most recent call last):
  File "/home/admin/probe/probe.py", line 722, in refresh_discovery
    zabbix_sender.send([discovery_metric])
  File "/home/admin/probe/.venv/lib/python3.5/site-packages/pyzabbix/sender.py", line 433, in send
    result.parse(self._chunk_send(metrics[m:m + self.chunk_size]))
  File "/home/admin/probe/.venv/lib/python3.5/site-packages/pyzabbix/sender.py", line 408, in _chunk_send
    logger.warn('Sending failed: %s', err.msg)
AttributeError: 'ConnectionRefusedError' object has no attribute 'msg'
```

**Comment by nijel** [comment]
Oops, sorry. Looks I've chosen wrong python zabbix module to report this. The issue is already reported at https://github.com/adubkov/py-zabbix/issues/125
