### ISSUE TITLE
Today's commit broke the installation via pip

### ISSUE THREAD

**Issue by juliosaraiva** [lukecyca/pyzabbix#138]
(.venv) PS C:\Users\julio\Documents\learning-python\test-scrapy> pip install --no-cache-dir pyzabbix
Collecting pyzabbix
  Downloading pyzabbix-0.8.1.tar.gz (5.1 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\julio\documents\learning-python\test-scrapy\.venv\scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\julio\\AppData\\Local\\Temp\\pip-install-bsavno8p\\pyzabbix\\setup.py'"'"'; __file__='"'"'C:\\Users\\julio\\AppData\\Local\\Temp\\pip-install-bsavno8p\\pyzabbix\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\julio\AppData\Local\Temp\pip-pip-egg-info-8h_ki9pe'
         cwd: C:\Users\julio\AppData\Local\Temp\pip-install-bsavno8p\pyzabbix\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\julio\AppData\Local\Temp\pip-install-bsavno8p\pyzabbix\setup.py", line 3, in <module>
        with open("README.markdown", "r") as fh:
    FileNotFoundError: [Errno 2] No such file or directory: 'README.markdown'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by juliosaraiva** [comment]
Sent PR
