### ISSUE TITLE
doesn't work with server self signed cerificates

### ISSUE THREAD

**Issue by UweW** [lukecyca/pyzabbix#162]
Hi,
the connectivity doen't work if the server has a self signed certificate:

`
from pyzabbix import ZabbixAPI
import urllib3
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

ZABBIX_SERVER = 'https://zabbix.xxxx.com'
api_token="116xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxeb"

zapi = ZabbixAPI(ZABBIX_SERVER )
zapi.session.verify = False

zapi.login(api_token=api_token)
`
ends every time in: 

Traceback (most recent call last):
  File "C:\Users\NQ10038885\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen      
    httplib_response = self._make_request(
  File "C:\Users\NQ10038885\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "C:\Users\NQ10038885\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "C:\Users\NQ10038885\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
  File "C:\Users\NQ10038885\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "C:\Users\NQ10038885\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\NQ10038885\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 512, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\NQ10038885\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1070, in _create
    self.do_handshake()
  File "C:\Users\NQ10038885\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1341, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\NQ10038885\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 440, in send
    resp = conn.urlopen(
  File "C:\Users\NQ10038885\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "C:\Users\NQ10038885\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='zabbix.xxxx.com', port=443): Max retries exceeded with url: /api_jsonrpc.php (**Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:997)')))**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\NQ10038885\Documents\zabbix\get_cpu.py", line 10, in <module>
    zapi = ZabbixAPI(ZABBIX_SERVER )
  File "C:\Users\NQ10038885\AppData\Local\Programs\Python\Python310\lib\site-packages\pyzabbix\__init__.py", line 73, in __init__
    self.api_version()
  File "C:\Users\NQ10038885\AppData\Local\Programs\Python\Python310\lib\site-packages\pyzabbix\__init__.py", line 145, in api_version
    return self.apiinfo.version()
  File "C:\Users\NQ10038885\AppData\Local\Programs\Python\Python310\lib\site-packages\pyzabbix\__init__.py", line 217, in fn
    return self.parent.do_request(
  File "C:\Users\NQ10038885\AppData\Local\Programs\Python\Python310\lib\site-packages\pyzabbix\__init__.py", line 162, in do_request
    response = self.session.post(
  File "C:\Users\NQ10038885\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 577, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Users\NQ10038885\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\NQ10038885\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\NQ10038885\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='zabbix.xxxx.com', port=443): Max retries exceeded with url: /api_jsonrpc.php **(Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:997)')))**

**Comment by belykhk** [comment]
Try

`zapi = ZabbixAPI(ZABBIX_SERVER, detect_version=False)`

**Comment by UweW** [comment]
detect_version = False works :-)

Thanks' a lot

**Comment by jooola** [comment]
For reference, one can also configure the verify parameter using the REQUESTS_CA_BUNDLE environment variable.

https://requests.readthedocs.io/en/latest/user/advanced/#ssl-cert-verification
