### ISSUE TITLE
Login not working - Error -32602: Invalid params., Not authorized.', -32602

### ISSUE THREAD

**Issue by chises** [lukecyca/pyzabbix#212]
Hello,

I try to connect to zabbix api but it is not working for me:
```
import sys
import logging
from pyzabbix import ZabbixAPI

stream = logging.StreamHandler(sys.stdout)
stream.setLevel(logging.DEBUG)
log = logging.getLogger('pyzabbix')
log.addHandler(stream)
log.setLevel(logging.DEBUG)


zapi = ZabbixAPI("http://ip/")
zapi.login("myuser", "mypassword")
print("Connected to Zabbix API Version %s" % zapi.api_version())

for h in zapi.host.get(output="extend"):
    print(h['hostid'])

```
The result:

```

JSON-RPC Server Endpoint: http://ip/api_jsonrpc.php
Sending: {'jsonrpc': '2.0', 'method': 'apiinfo.version', 'params': {}, 'id': 0}
Response Code: 200
Response Body: {'jsonrpc': '2.0', 'result': '6.4.2', 'id': 0}
Zabbix API version is: 6.4.2
Sending: {'jsonrpc': '2.0', 'method': 'user.login', 'params': {'username': 'myuser', 'password': 'mypassword'}, 'id': 1}
Response Code: 200
Response Body: {'jsonrpc': '2.0', 'result': 'c6162932116ce1cc065d16414632ccc4', 'id': 1}
Sending: {'jsonrpc': '2.0', 'method': 'apiinfo.version', 'params': {}, 'id': 2}
Response Code: 200
Response Body: {'jsonrpc': '2.0', 'result': '6.4.2', 'id': 2}
Connected to Zabbix API Version 6.4.2
Sending: {'jsonrpc': '2.0', 'method': 'host.get', 'params': {'output': 'extend'}, 'id': 3}
Response Code: 200
Response Body: {'jsonrpc': '2.0', 'error': {'code': -32602, 'message': 'Invalid params.', 'data': 'Not authorized.'}, 'id': 3}
Traceback (most recent call last):
  File "c:\Users\user\OneDrive\test.py", line 16, in <module>
    for h in zapi.host.get(output="extend"):
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\Python\Python311\site-packages\pyzabbix\api.py", line 278, in __call__
    return self._parent.do_request(self._method, args or kwargs)["result"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\Python\Python311\site-packages\pyzabbix\api.py", line 249, in do_request
    raise ZabbixAPIException(
pyzabbix.api.ZabbixAPIException: ('Error -32602: Invalid params., Not authorized.', -32602)
```

Login for this user is fine and API key is not working, too. Any ideas? Thank you!

**Comment by chises** [comment]
Seems to be a issue on zabbix Site.
Zabbix Forum: https://www.zabbix.com/forum/zabbix-troubleshooting-and-problems/465800-python-api-modules-not-working-with-6-4
Zabbix Bug Report: https://support.zabbix.com/browse/ZBX-22952

**Comment by ghost** [comment]
I got the same error and the workaround on apache2/nginx posted in the Zabbix Bug Report did not work for me.
I downgraded pyzabbix to 0.8.2 and it works with username/pw authentication only (not with apitoken of course).

With **pyzabbix v. 0.8.2** you have to change the parameter **user** to **username** when using nexer versions of Zabbix:

```
  def login(self, user='', password=''):
        """Convenience method for calling user.authenticate and storing the resulting auth token
           for further commands.
           If use_authenticate is set, it uses the older (Zabbix 1.8) authentication command
           :param password: Password used to login into Zabbix
           :param user: Username used to login into Zabbix
        """

        # If we have an invalid auth token, we are not allowed to send a login
        # request. Clear it before trying.
        self.auth = ''
        if self.use_authenticate:
            self.auth = self.user.authenticate(username=user, password=password)
        else:
            self.auth = self.user.login(username=user, password=password)
```
