### ISSUE TITLE
MissingSchema exception

### ISSUE THREAD

**Issue by vbmade2000** [lukecyca/pyzabbix#67]
I am trying following example from Github tutorial.

from pyzabbix import ZabbixAPI

zapi = ZabbixAPI("localhost")
zapi.login("admin", "zabbix")
print "Connected to Zabbix API Version %s" % zapi.api_version()

for h in zapi.host.get(output="extend"):
    print h['hostid']

=========================================================

I have Ubuntu 15 system on which zabbix-server is running. I am executing above example on same system. I get the following:

Traceback (most recent call last):
  File "pyzabbixdemo.py", line 4, in <module>
    zapi.login("admin", "zabbix")
  File "/home/seagate/Documents/pyzabbix/pyzabbixdemo/local/lib/python2.7/site-packages/pyzabbix/__init__.py", line 68, in login
    self.auth = self.user.login(user=user, password=password)
  File "/home/seagate/Documents/pyzabbix/pyzabbixdemo/local/lib/python2.7/site-packages/pyzabbix/__init__.py", line 156, in fn
    args or kwargs
  File "/home/seagate/Documents/pyzabbix/pyzabbixdemo/local/lib/python2.7/site-packages/pyzabbix/__init__.py", line 101, in do_request
    timeout=self.timeout
  File "/home/seagate/Documents/pyzabbix/pyzabbixdemo/local/lib/python2.7/site-packages/requests/sessions.py", line 508, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/seagate/Documents/pyzabbix/pyzabbixdemo/local/lib/python2.7/site-packages/requests/sessions.py", line 451, in request
    prep = self.prepare_request(req)
  File "/home/seagate/Documents/pyzabbix/pyzabbixdemo/local/lib/python2.7/site-packages/requests/sessions.py", line 382, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/seagate/Documents/pyzabbix/pyzabbixdemo/local/lib/python2.7/site-packages/requests/models.py", line 304, in prepare
    self.prepare_url(url, params)
  File "/home/seagate/Documents/pyzabbix/pyzabbixdemo/local/lib/python2.7/site-packages/requests/models.py", line 362, in prepare_url
    to_native_string(url, 'utf8')))
requests.exceptions.MissingSchema: Invalid URL 'localhost/api_jsonrpc.php': No schema supplied. Perhaps you meant http://localhost/api_jsonrpc.php?

Can anyone tell me what is wrong here because as a beginner I am not able to figure out ?

**Comment by neothematrix** [comment]
Hi, this is not supposed to be an help forum, but it should be used to notify possible bugs.
Anyway, your error is that you cannot use "localhost" as URL for the ZabbixAPI() instance, the error message actually even told you how to fix it: use 'http://localhost/' (or most probably http://localhost/zabbix/) when you call "zapi = ZabbixAPI()".
